// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dberzwsxgksjgsqanimu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiZXJ6d3N4Z2tzamdzcWFuaW11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwODQ4NTMsImV4cCI6MjA3MDY2MDg1M30.OZoMMem3tcd1O7XURBsVwTmrs0Ex3QfHQSfSFPG9m3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});